### ISSUE TITLE
using jackson streaming api for large amounts of json

### ISSUE THREAD

**Issue by henryw374** [metosin/jsonista#42]
I've created a gist to show reading and writing json in a streamed style - specifically where you have a large array of objects. https://gist.github.com/henryw374/5e41464d386942910b50d1af02bded61 not sure if you had thought about adding something like this to the api or not, but anyway.. still handy to have a demo example 

... and if you can see any mistakes there please let me know ;-)

Thanks

**Comment by ohpauleez** [comment]
I've used a similar approach in the projects where I needed streams of JSON.  I tend to use reducibles/reducible-seqs instead of actual Sequences/lazy-seq.  You can make some other smaller tweaks to keep GC churn low and application throughput a bit higher if your application is centered around the JSON stream.

**Comment by bsless** [comment]
see #53 and #55, possibly coming soon

**Comment by opqdonut** [comment]
See docs/streaming.md

**Comment by henryw374** [comment]
new streaming api looks good. cheers
